# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='E0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e0oppm', models.CharField(max_length=12)),
                ('e0module', models.CharField(max_length=20)),
                ('e0efforts', models.DecimalField(decimal_places=2, max_digits=4)),
                ('e0updtdte', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='E1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e1oppm', models.CharField(max_length=12)),
                ('e1module', models.CharField(max_length=20)),
                ('e1efforts', models.DecimalField(decimal_places=2, max_digits=4)),
                ('e1providedte', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('oppm', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('release', models.CharField(max_length=7)),
                ('title', models.CharField(max_length=100)),
                ('pv', models.CharField(max_length=10)),
                ('impactedcountries', models.CharField(max_length=20)),
                ('impactedpps', models.CharField(max_length=50)),
                ('funding', models.CharField(max_length=20)),
                ('invtype', models.CharField(max_length=20)),
                ('invcat', models.CharField(max_length=20)),
                ('requestchannel', models.CharField(max_length=10)),
                ('bsgleadba', models.CharField(max_length=30)),
                ('bsgba', models.CharField(max_length=7)),
                ('pm', models.CharField(max_length=30)),
                ('adddte', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RelCalendar',
            fields=[
                ('releaseid', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('planningstartdte', models.DateTimeField()),
                ('planningenddte', models.DateTimeField()),
                ('initstartdte', models.DateTimeField()),
                ('initenddte', models.DateTimeField()),
                ('defnstartdte', models.DateTimeField()),
                ('defnenddte', models.DateTimeField()),
                ('designstartdte', models.DateTimeField()),
                ('designenddte', models.DateTimeField()),
                ('constrstartdte', models.DateTimeField()),
                ('constrenddte', models.DateTimeField()),
                ('valsitstartdte', models.DateTimeField()),
                ('valsitenddte', models.DateTimeField()),
                ('valuatstartdte', models.DateTimeField()),
                ('valuatenddte', models.DateTimeField()),
                ('implstartdte', models.DateTimeField()),
                ('implenddte', models.DateTimeField()),
            ],
        ),
    ]
