# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('oppm', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('pv', models.CharField(max_length=10)),
                ('impactedcountries', models.CharField(max_length=20)),
                ('impactedpps', models.CharField(max_length=50)),
                ('funding', models.CharField(max_length=20)),
                ('invtype', models.CharField(max_length=20)),
                ('invcat', models.CharField(max_length=20)),
                ('invsubcat', models.CharField(max_length=20)),
                ('requestchannel', models.CharField(max_length=10)),
                ('bsgleadba', models.CharField(max_length=30)),
                ('bsgba', models.CharField(max_length=7)),
                ('pm', models.CharField(max_length=30)),
                ('adddte', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('remarks', models.TextField()),
            ],
        ),
    ]
