# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relapp', '0002_project_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implenddte', models.DateTimeField()),
            ],
        ),
    ]
